
version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests.test_parse_input_file

  build:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests.test_parse_input_file
