
version: 2.1
jobs:
  test3_6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests.test_parse_input_file

  test2_7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest tests.test_parse_input_file


workflows:
  test:
    jobs:
      - test3_6
      - test2_7
